// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAahKQGC0qjHmA7weRPelYrIUjCMPaQ_5U',
    appId: '1:725088718546:web:a18003c9a8eb9fe939270b',
    messagingSenderId: '725088718546',
    projectId: 'cfa---courses-for-all',
    authDomain: 'cfa---courses-for-all.firebaseapp.com',
    storageBucket: 'cfa---courses-for-all.appspot.com',
    measurementId: 'G-PNER3VN41M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXdMdVLQW1bYo4hamfCK3YAACjjOpvZXY',
    appId: '1:725088718546:android:a718642f19d22e0239270b',
    messagingSenderId: '725088718546',
    projectId: 'cfa---courses-for-all',
    storageBucket: 'cfa---courses-for-all.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgoJH2sdq755BzazDqWCDs-AHiUIDmPK8',
    appId: '1:725088718546:ios:015a4e3ded13afbb39270b',
    messagingSenderId: '725088718546',
    projectId: 'cfa---courses-for-all',
    storageBucket: 'cfa---courses-for-all.appspot.com',
    iosBundleId: 'com.example.cfaCoursesforall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgoJH2sdq755BzazDqWCDs-AHiUIDmPK8',
    appId: '1:725088718546:ios:6ece8bfc61b4a6ff39270b',
    messagingSenderId: '725088718546',
    projectId: 'cfa---courses-for-all',
    storageBucket: 'cfa---courses-for-all.appspot.com',
    iosBundleId: 'com.example.cfaCoursesforall.RunnerTests',
  );
}
